version: 0.2



phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y git-core build-essential libssl-dev libncurses5-dev unzip gawk zlib1g-dev
      - adduser openwrt
  build:
    run-as: openwrt
    commands:
      - echo Build started on `date`
      - git clone https://www.github.com/openwrt/openwrt
      - cd openwrt
      - ./scripts/feeds update -a
      - ./scripts/feeds install -a
      - cp ../erx-config ./.config
      - make -j1 V=s
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - hello.out
